// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    PageNavbar: typeof import('./src/components/PageNavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
